services:
  - type: web
    name: jamaat-tracker-api
    runtime: node
    region: frankfurt
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    instanceType: free
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
